### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by tinvaan** [tinvaan/drone-python#2]
We have the setup script in place to build the package. Make it publicly available in the [Python Package Index](https://pypi.org/)

**Comment by DanB288** [comment]
Hey @tinvaan !!, I would like solve this issue. Can you assign it to me?

**Comment by tinvaan** [comment]
@DanB288 thanks for your interest. This issue is assigned to you now.

**Comment by tinvaan** [comment]
I'm taking this up due to inactivity. First draft package already published at https://pypi.org/project/drone-python/
