### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by tinvaan** [tinvaan/drone-python#3]
This project is free in every sense. What's a good license we could use for this ?

**Comment by ghost** [comment]
how about MIT?

**Comment by tinvaan** [comment]
> how about MIT?

@jiyoungsin I'm inclining towards the Apache 2.0 license. It seems to be a more fine tuned MIT license in some sense. I doubt it would really matter for a project such as this, still in it's infancy.

**Comment by tinvaan** [comment]
Fixed in https://github.com/tinvaan/PyDroneio/pull/8. Feel free to reopen if needed.
