### ISSUE TITLE
You don't need to alter the `requests.patch` calling semantics based on whether your method was passed `params` or `data` content

### ISSUE THREAD

**Issue by ianchesal** [tinvaan/drone-python#4]
https://github.com/tinvaan/PyDroneio/blob/d89d042e6938685e341e15014ef379604a4670e8/drone/http.py#L20

You don't need to check `params` and `data` like you're doing here and change the calling semantics for `request.post()`. You can simplify all of this down to:

```python
    r = requests.patch(url, headers=headers, params=params, data=data)
    if not r.ok:
        r.raise_for_status()
    return r.json()
```

This applies to all the methods you have in this class that call `requests` methods like this (`patch` and `get`).

**Comment by tinvaan** [comment]
@ianchesal thanks for pointing this out. I've addressed this in #6 and will merge shortly. Feel free to reopen if you feel anything lacking.

P.S: Apologies this took so long. Life away from work needed immediate attention :)
