### ISSUE TITLE
Nowhere mentioned you have to set DRONE_TOKEN and DRONE_SERVER in Readme.md

### ISSUE THREAD

**Issue by alexrjs** [tinvaan/drone-python#5]
It is nowhere mentioned you have to set DRONE_TOKEN and DRONE_SERVER in Readme.md in the example section. But without them it does not work. So this should be mentioned.

Anyway thanks for publishing, since I need exactly your library to try to solve my problem of depended build triggering from a running pipeline over the api.

So thank you and keep your good work up2date.

Cheers

**Comment by tinvaan** [comment]
@alexrjs sorry it took me so long to merge the open PR. Had to deal with a few things away from work recently. Thanks for your help!
